grep '	FieldQuantity	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
grep '	ParticleQuantity	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
grep '	MeasurementType	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
grep '	ParticleType	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
grep '	DirectionAngle	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
grep '	MixedQuantity	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
grep '	SpectralRange	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
grep '	WaveQuantity	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
grep '	WaveType	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
grep '	InstrumentType	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
grep '	ProcCoefType	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
grep '	ProcessType	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
grep '	Product	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
grep '	SupportQuantity	' /home/jovyan/lbargatze/Space/PROGRAMS/HARVEST/SPASE/SCHEMA/TAB_FILES/2_6_0/member.tab
