grep -c " mvn_insitu_kp-4sec " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_mag_l2-sunstate-1sec " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_sep_l2_s1-cal-svy-full " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_sep_l2_s2-cal-svy-full " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_sta_l2_d8-12r1e " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_sta_l2_d9-12r64e " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_sta_l2_da-1r64e " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_swe_l2_arc3d " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_swe_l2_arcpad " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_swe_l2_svy3d " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_swe_l2_svypad " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_swe_l2_svyspec " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_swi_l2_coarsearc3d " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_swi_l2_coarsesvy3d " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_swi_l2_finearc3d " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_swi_l2_finesvy3d " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_swi_l2_onboardsvymom " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
grep -c " mvn_swi_l2_onboardsvyspec " /home/jovyan/efs/lbargatze/cdaweb_harvest_wrapper_all_mvn.com
